//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cleaner()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public string CleanerDNI { get; set; }
        public string CleanerNombre { get; set; }
        public string CleanerNumero { get; set; }
        public System.DateTime CleanerFechaNacimiento { get; set; }
        public string CleanerProvincia { get; set; }
        public string CleanerSexo { get; set; }
        public string CleanerContrasena { get; set; }
        public string CleanerEstado { get; set; }
        public decimal CleanerSueldo { get; set; }
        public byte[] CleanerFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
