//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int ComprobanteId { get; set; }
        public string ReservaId { get; set; }
        public System.DateTime ComprobanteFechaEmision { get; set; }
        public string ComprobanteMetodoPago { get; set; }
        public decimal ComprobanteMontoTotal { get; set; }
    
        public virtual Reserva Reserva { get; set; }
    }
}
