//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Comprobante = new HashSet<Comprobante>();
        }
    
        public string ReservaId { get; set; }
        public string CleanerDNI { get; set; }
        public string ClienteDNI { get; set; }
        public int ServicioId { get; set; }
        public string ReservaDireccion { get; set; }
        public string ReservaProvincia { get; set; }
        public System.DateTime ReservaFechaCreacion { get; set; }
        public System.DateTime ReservaFechaProgramada { get; set; }
        public Nullable<System.DateTime> ReservaFechaInicio { get; set; }
        public Nullable<System.DateTime> ReservaFechaTerminado { get; set; }
        public System.TimeSpan ReservaHora { get; set; }
        public string ReservaEstado { get; set; }
        public string ReservaObservacion { get; set; }
    
        public virtual Cleaner Cleaner { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
